version: '2'
services:
  shell:
    build:
      context: .
      dockerfile: ./docker/shell/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
  air:
    build:
      context: .
      dockerfile: ./docker/air/Dockerfile
    ports:
      - '4201:4201'
    volumes:
      - .:/app
  ocean:
    build:
      context: .
      dockerfile: ./docker/ocean/Dockerfile
    ports:
      - '4202:4202'
    volumes:
      - .:/app
