version: '3.0'
services:
  shell:
    image: comparativo-shell
    pull_policy: never
    build:
      context: .
      dockerfile: ./docker/shell/Dockerfile
    ports:
      - '4200:4200'
  air:
    build: ./docker/air
    ports:
      - '4201:4201'
    depends_on:
      - shell
  ocean:
    build: ./docker/ocean
    ports:
      - '4202:4202'
    depends_on:
      - shell
